name: test

on: push

jobs:
  unit-test:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Go setup
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'

      - name: Run unit tests
        run: make test

  push-images:
    runs-on: ubuntu-18.04
    needs: unit-test

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Log into container registry
        run: echo ${{ secrets.DockerHubToken }} | docker login --username timoreimann --password-stdin

      - name: build and push runner image
        run: RUNNER_IMAGE=timoreimann/k8s-e2e-test-runner RUNNER_IMAGE_TAG_PREFIX=$(basename $GITHUB_REF)- make runner-push

      - name: Build and push plugin image
        run: DOCKER_REPO=timoreimann/do-csi-plugin-dev VERSION=$(basename $GITHUB_REF) make compile build push

  e2e-test:
    runs-on: ubuntu-18.04
    needs: push-images
    strategy:
      matrix:
        kube-release: ['1.16', '1.15', '1.14']

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Go setup
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'

      - name: Install kustomize
        env:
          KUSTOMIZE_VERSION: '3.5.3'
        run: curl -fL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz | sudo tar xzv -C /usr/local/bin kustomize

      - name: Run end-to-end tests
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.CSIDigitalOceanAccessToken }}
        run: TIMEOUT=60m make test-e2e E2E_ARGS="-driver-image timoreimann/do-csi-plugin-dev:$(basename $GITHUB_REF) -runner-image timoreimann/k8s-e2e-test-runner:$(basename $GITHUB_REF)-latest -name-suffix $(basename $GITHUB_REF) ${{ matrix.kube-release }}"
