### Run unit as well as end-to-end tests on PRs and master pushes. For the
### latter, we also push a new CSI plugin master image to the container
### registry.
name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:

jobs:
  unit-test:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Go setup
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'

      - name: Run unit tests
        run: make

  push-images:
    runs-on: ubuntu-18.04
    needs: unit-test

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Log into container registry
        run: echo ${{ secrets.DockerHubToken }} | docker login --username timoreimann --password-stdin

      - name: build and push runner image
        env:
          # ${{ github.head_ref }} is empty for non-pull requests, which is
          # exactly what we want on master.
          RUNNER_IMAGE_TAG_PREFIX: ${{ github.head_ref }}
        run: RUNNER_IMAGE=timoreimann/k8s-e2e-test-runner make runner-push

      - name: Build and push plugin image
        env:
          VERSION: ${{ github.head_ref }}
        run: |
          VERSION="${VERSION:-latest}"
          DOCKER_REPO=timoreimann/do-csi-plugin-dev make compile build push

  e2e-test:
    runs-on: ubuntu-18.04
    needs: push-images
    strategy:
      matrix:
        kube-release: ['1.16', '1.15', '1.14']

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Go setup
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'

      - name: Install kustomize
        env:
          KUSTOMIZE_VERSION: '3.5.3'
        run: curl -fL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz | sudo tar xzv -C /usr/local/bin kustomize

      - name: Run end-to-end tests
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.CSIDigitalOceanAccessToken }}
          BRANCH: ${{ github.head_ref }}
        run: |
          NAME_SUFFIX="${BRANCH}"
          TAG="${BRANCH}"
          if [[ $BRANCH != "" ]]; then
            RUNNER_IMAGE_TAG_PREFIX=${BRANCH}-
          else
            NAME_SUFFIX=master
            TAG=latest
          fi
          TIMEOUT=60m make test-e2e E2E_ARGS="-ginkgo-nodes 3 -driver-image timoreimann/do-csi-plugin-dev:${TAG} -runner-image timoreimann/k8s-e2e-test-runner:${RUNNER_IMAGE_TAG_PREFIX}latest -name-suffix ${NAME_SUFFIX} ${{ matrix.kube-release }}"

  tag-new-master-image:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    needs: e2e-test

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Log into container registry
        run: echo ${{ secrets.DockerHubToken }} | docker login --username timoreimann --password-stdin

      - name: tag new CSI plugin master image
        run: |
          docker pull timoreimann/do-csi-plugin-dev:latest
          docker tag timoreimann/do-csi-plugin-dev:latest timoreimann/do-csi-plugin:master
          docker push timoreimann/do-csi-plugin:master
